
defaults: &defaults
  working_directory: ~/deno-pretty-assert
  docker:
    - image: maxmcd/deno
      environment:
        TZ: Asia/Tokyo
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - run:
          name: Install others
          command: |
            apt-get install -y python3 python3-pip fonts-migmix
            pip3 install awscli
            npm i -g firebase-tools
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Tsc
          command: yarn run tsc     
      - run:
          name: Test
          command: yarn run test                    
