
defaults: &defaults
  working_directory: ~/deno-pretty-assert
  docker:
    - image: maxmcd/deno
      environment:
        TZ: Asia/Tokyo
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test
          command: deno index.test.ts
